keys:
  # TODO: replace with the public key from: age-keygen -o /var/lib/sops-nix/key.txt
  - &server age1xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

creation_rules:
  - path_regex: secrets\.yaml$
    key_groups:
      - age:
          - *server
